package org.poolc.api.drive.controller;
import lombok.RequiredArgsConstructor; import org.poolc.api.drive.domain.DriveItem; import org.poolc.api.drive.dto.DriveItemResponse; import org.poolc.api.drive.service.DriveService; import org.poolc.api.file.service.FileStorage; import org.poolc.api.file.service.StoredFile; import org.poolc.api.member.domain.Member; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.IOException; import java.util.*;
@RestController @RequiredArgsConstructor @RequestMapping("/drive") public class DriveController { private final DriveService service; private final FileStorage storage;
 @GetMapping public List<DriveItemResponse> list(@AuthenticationPrincipal Member member,@RequestParam(required=false) Long parentId){return service.list(member,parentId);}
 @PostMapping("/folders") public DriveItemResponse folder(@AuthenticationPrincipal Member member,@RequestBody Map<String,Object> body){return service.createFolder(member,body.get("parentId")==null?null:Long.valueOf(body.get("parentId").toString()),String.valueOf(body.get("name")));}
 @PostMapping(value="/files",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public DriveItemResponse upload(@AuthenticationPrincipal Member member,@RequestParam(required=false) Long parentId,@RequestPart MultipartFile file)throws IOException{return service.upload(member,parentId,file);}
 @PutMapping("/{id}/shares") public DriveItemResponse share(@AuthenticationPrincipal Member member,@PathVariable Long id,@RequestBody Map<String,List<String>> body){return service.share(member,id,body.get("memberLoginIds"));}
 @GetMapping("/{id}/download") public ResponseEntity<byte[]> download(@AuthenticationPrincipal Member member,@PathVariable Long id)throws IOException{DriveItem item=service.item(member,id); if(item.getType().name().equals("FOLDER"))throw new IllegalArgumentException("폴더는 다운로드할 수 없습니다."); try(StoredFile stored=storage.load(item.getStorageId())){return ResponseEntity.ok().contentType(item.getContentType()==null?MediaType.APPLICATION_OCTET_STREAM:MediaType.parseMediaType(item.getContentType())).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(item.getName(),java.nio.charset.StandardCharsets.UTF_8).build().toString()).body(stored.getInputStream().readAllBytes());}}
}
